name: CI

env:
    APPLICATION_ENV: 'development'
    APPLICATION_STORE: 'DE'
    PROJECT: 'EventBehavior'
    DATABASE_VERSION: mariadb-10.11
    DATABASE_HOST: 127.0.0.1
    DATABASE_PORT: 3306
    DATABASE_NAME: eu-docker
    DATABASE_USERNAME: spryker
    DATABASE_PASSWORD: secret
    DATABASE_ROOT_PASSWORD: secret
    DATABASE_ALLOW_EMPTY_PASSWORD: false
    DATABASE_CHARACTER_SET: utf8
    DATABASE_COLLATE: utf8_general_ci

on:
    pull_request:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    validation:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: [
                    '8.3',
                    '8.4'
                ]

        services:
            mysql:
                image: mariadb:10.11
                env:
                    MYSQL_ROOT_PASSWORD: secret
                    MYSQL_DATABASE: eu-docker
                    MYSQL_USER: spryker
                    MYSQL_PASSWORD: secret
                    MARIADB_CHARACTER_SET_SERVER: utf8
                    MARIADB_COLLATION_SERVER: utf8_general_ci
                ports:
                    - 3306:3306
                options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring, intl, pdo_mysql

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-lock-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Composer install
                run: |
                    composer --version
                    composer install --optimize-autoloader

            -   name: Run tests
                run: composer test

            -   name: PHPStan checks
                run: |
                    composer stan-setup
                    composer stan

            -   name: CodeStyle checks
                run: composer cs-check

    prefer-lowest:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: [
                    '8.3'
                ]

        services:
            mysql:
                image: mariadb:10.11
                env:
                    MYSQL_ROOT_PASSWORD: secret
                    MYSQL_DATABASE: eu-docker
                    MYSQL_USER: spryker
                    MYSQL_PASSWORD: secret
                    MARIADB_CHARACTER_SET_SERVER: utf8
                    MARIADB_COLLATION_SERVER: utf8_general_ci
                ports:
                    - 3306:3306
                options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring, intl, pdo_mysql

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Composer prefer-lowest
                run: composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable -o

            -   name: Run tests
                run: composer test

            -   name: PHPStan checks
                run: |
                    composer stan-setup
                    composer stan
